name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: openapi lint
        uses: trybeapp/redocly-openapi-cli-github-action@v1
        with:
          args: 'lint note-api.yaml'
